// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AllCategoriesMenu: typeof import('./components/AppNavbar/components/AllCategoriesMenu.vue')['default']
    AppBanner: typeof import('./components/AppBanner/index.vue')['default']
    AppCategories: typeof import('./components/AppCategories/index.vue')['default']
    AppFilter: typeof import('./components/AppFilter/index.vue')['default']
    AppFooter: typeof import('./components/AppFooter/index.vue')['default']
    AppHeader: typeof import('./components/AppHeader/index.vue')['default']
    AppNavbar: typeof import('./components/AppNavbar/index.vue')['default']
    AutoGrid: typeof import('./components/base/AutoGrid.vue')['default']
    BaseButton: typeof import('./components/base/BaseButton.vue')['default']
    BaseContent: typeof import('./components/base/BaseContent.vue')['default']
    BaseForm: typeof import('./components/base/BaseForm.vue')['default']
    BasePopup: typeof import('./components/base/BasePopup.vue')['default']
    Carousel: typeof import('./components/base/Carousel.vue')['default']
    Cart: typeof import('./components/AppNavbar/components/Cart.vue')['default']
    ContentLoader: typeof import('./components/base/ContentLoader.vue')['default']
    DashboardNavbar: typeof import('./components/DashboardNavbar/index.vue')['default']
    DashboardOverviewContent: typeof import('./components/DashboardOverviewContent/index.vue')['default']
    EmptyContent: typeof import('./components/base/EmptyContent.vue')['default']
    HomeCategorySection: typeof import('./components/HomeCategorySection/index.vue')['default']
    LoaderApp: typeof import('./components/base/LoaderApp.vue')['default']
    MountedTeleport: typeof import('./components/base/MountedTeleport.vue')['default']
    Notifications: typeof import('./components/AppNavbar/components/Notifications.vue')['default']
    NotificationsSummary: typeof import('./components/NotificationsSummary/index.vue')['default']
    OverviewFooter: typeof import('./components/OverviewFooter/index.vue')['default']
    OverviewHeader: typeof import('./components/DashboardOverviewContent/components/OverviewHeader.vue')['default']
    PrimeSideBar: typeof import('./components/base/PrimeSideBar.vue')['default']
    ProductDescription: typeof import('./components/ProductDescription/index.vue')['default']
    ProductDetails: typeof import('./components/ProductDetails/index.vue')['default']
    ProductMainCard: typeof import('./components/ProductMainCard/index.vue')['default']
    ProductReviews: typeof import('./components/ProductReviews/index.vue')['default']
    ProductSecondaryCard: typeof import('./components/ProductSecondaryCard/index.vue')['default']
    ProductSliderList: typeof import('./components/ProductSliderList/index.vue')['default']
    ProductSpecifications: typeof import('./components/ProductSpecifications/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Search: typeof import('./components/AppNavbar/components/Search.vue')['default']
    SelectBox: typeof import('./components/base/SelectBox.vue')['default']
    ShortcutsComponent: typeof import('./components/AppFilter/components/ShortcutsComponent.vue')['default']
    StatsCard: typeof import('./components/StatsCard/index.vue')['default']
    TheFooter: typeof import('./components/base/TheFooter.vue')['default']
    UserMenu: typeof import('./components/AppNavbar/components/UserMenu.vue')['default']
    Wishlist: typeof import('./components/AppNavbar/components/Wishlist.vue')['default']
  }
}
